### ISSUE TITLE
use cases for enhancing and editing externally created metadata (previously known as "import" metadata into editor)

### ISSUE THREAD

**Issue by cmharlow** [LD4P/sinopia#61] opened 2018-07-17 23:18 UTC
Import pre-created metadata into the editor across profiles.

Edit metadata created in another tool

**Comment by michelleif** [comment] 2018-08-10 21:15
does this cover using MARC records converted by Casalini/Share-VDE? stated goal in project proposal is create a "continuously fed pool of linked data expressed in BIBFRAME from a core group of libraries". Vision is that libraries convert their MARC via Casalini (or other conversion service) and converted data is "usable" in sandbox. What "usable" means, and what "continuously fed" means are TBD.

**Comment by michelleif** [comment] 2018-09-12 16:38
from actual user:
"I have a new book in hand. I find the work and the instance [already cataloged], but the instance data is very sparse. I want to add more statements about the instance (e.g., a second contributor, another subject heading, a genre term). (Again, this could also apply to a work). This scenario will be very common, because original cataloging will mostly be built on order records that have been converted from MARC. There is very little cataloging that actually happens from a blank slate."

**Comment by michelleif** [comment] 2018-09-12 16:40
from another user:
“As a cataloger I can edit converted data by making changes to the source data and rerunning the conversion process.”

**Comment by michelleif** [comment] 2018-09-13 20:54
use case from LC: "almost all of the current cataloging in the LC pilot starts with the cataloger loading a brief description that was converted from MARC. The cataloger adds additional info about the item and posts the updated description back to our BIBFRAME database."

**Comment by elrayle** [comment] 2018-09-18 14:52
### Requirements that seem clear and agreed upon...

* user can search external data sources (e.g. Share VDE and potentially others) for existing data on a work or instance
* user can copy existing data from a work or instance in an external data source into a Sinopia work or instance
* user can modify data copied in from an external data source and save changes in the Sinopia work or instance
* user can add additional data and save additions in the Sinopia work or instance

### Requirement Clarifications Needed...

* Does the Sinopia work or instance have a `sameas` or `seealso` triple to the original external source work or instance?
* Is there a workflow in which the external data source is updated with changes saved to Sinopia?

### Additional Considerations...

* If external data sources are locally cached...
  * is the cache READONLY?  (I would expect READONLY, as the alternative would be complex.)
  * what is the process for refreshing the cache?
  * when the cache is updated, does this impact any data already saved to Sinopia?

**Comment by michelleif** [comment] 2018-09-18 16:35
Re the above "Requirement Clarifications Needed":
- Will all Share VDE works and instances be imported into Sinopia up front? Or as they are needed?
_From user point of view, it doesn't matter where they are_
- Does the Sinopia work or instance have a sameas or seealso triple to the original external source work or instance?
_not something I can answer from user standpoint_
- Is there a workflow in which the external data source is updated with changes saved to Sinopia?
_this is a big question that will need to be explored as institutions start using Sinopia. Institutions do want to experiment with this workflow. But we have set the expectation with Sinopia users that Sinopia does **not** offer automatic syncing or roundtripping of data--at least not in early releases. But that they can export data from Sinopia to start to figure out this workflow. Part of the question is what's external and what's internal when talking about linked data?_

**Comment by michelleif** [comment] 2019-04-12 17:22
Note: we are currently thinking of things as "natively created in Sinopia" vs "created externally" (including MARC data converted by Casalini/Share-VDE), because that's how our architecture is set up. This ticket is collecting use cases for working with data that comes from various sources, with the hope of gathering user needs and eventually finding an architecture that supports those needs.

**Comment by michelleif** [comment] 2019-04-12 17:22
from Slack April 2019: NLM would like to be able to edit existing serials data, i.e., data that has been converted by SVDE/Casalini to BF.  Serials are live resources that undergo changes that do not necessarily result in new Works or Instances.  The easiest example is a change in frequency, e.g., a journal changes from being issued quarterly to being issued monthly.  We want to ADD (not replace, because the old frequency is still pertinent to a certain coverage period) that new frequency to the existing serial graph along with information about when the new frequency started and when the old frequency ended.  The latter might mean editing an existing triple by closing a date range.  Currently BF has no properties specifically for start and end dates, so we either have to deprecate the original triple and create a new one with a closed date range or change the original triple by closing the date or add a note that says we know the frequency changed but we're not entirely sure when it happened because we have a gap in coverage and it happened during that gap.  This is a common scenario that occurs with several different data points in serials cataloging.  We don't want to clone the original serial graph (it's a waste of storage), just add to it or edit existing data, and we want to share the new info with the entire community - it's not local data.

**Comment by michelleif** [comment] 2019-04-12 19:00
use cases from Harvard, from email in Sept 2018:

Regarding "fixing" a converted BF description, like correcting a typo: "This question depends on whether or not converted data is loaded into Sinopia; if so we would want to “fix” bad data. That said, we’d prefer that converted descriptions not be loaded into Sinopia by default; we’d rather bring pieces of description in selectively to create new descriptions and sidestep issues of data divergence and prompt to the cataloger to “fix” or improve statements at that point (typos in strings, manual entification/reconciliation of strings, etc). (We've seen something along these lines in OCLC's Linked Data Prototype project.)

more ideas:
Example/wishful thinking that may be out of scope: When bringing in an assertion about publication, could we do it in a way that moves us toward entification of publishers? So that by selecting a publisher we would then be referred to the most common transcribed literals used by a given publisher for selection and their equivalent URIs; within the context of reusing converted data, the retrieval tool might give us the most commonly found representations for a given publisher, and then allow the user to select which set of statements to bring into Sinopia for use."

Re deriving:
"For original cataloging in current practice, we generally derive from an existing record where much of the data will be the same, knowing that we will delete some; or we use templates for data that will stay the same for (e.g., basic resource format elements, common publisher/subject content). For linked data description of resources, we wouldn’t need to derive all of the data elements, but should be able to select the individual statements we want to reproduce in our new description.

we would also want to reuse elements while changing or adapting some, e.g., in a print to electronic conversion, dvd/blu-ray from vhs, etc.

Re searching and filtering:
Something like search templates would be helpful, especially for specific carrier types. For media formats, this could parallel some of the logic used in the 007 guided entry. The interface would guide you through the selection process and then retrieve the desired elements--it wouldn’t really matter which record that they came from. One question is if this is something that could be populated in Sinopia in advance, i.e., since there are a finite number of possible carriers/carrier descriptions, do you simply prepopulate these statements, either natively or by retrieval from existing converted descriptions?

PCC level says something about a record as a whole, I’m not sure how much meaning this has if we are examining statements individually and out of their original MARC record context. We’d be better off with the capability of filtering based on
1.	Absence or presence of URI
3.	Namespace of URI
4.	Descriptive convention/cataloging
5.	 source can be useful. E.g. certain workflows that are occasional and have a local best practice description, but you can’t remember a specific title to use as an exemplar, and a general search for that type of resource would result in too many hits lacking
6.	 the local description (this is more likely to be used in special collections cataloging, and obviously works better for smaller units).

**Comment by michelleif** [comment] 2019-04-12 19:01
from UCSD Slack message: We were also hoping to be able to update existing descriptions, without recreating them, for example to add information about Creative Commons licensing for our OA resources or even add new links, etc.

**Comment by michelleif** [comment] 2019-06-25 14:03
also see Steven Folsom's "A Pragmatic Approach to Using Discogs in an RDF Copy Cataloging Workflow" https://drive.google.com/drive/folders/1KP90kjhAMLjW0KJimvCC2m44eDEK6on4

**Comment by michelleif** [comment] 2019-09-08 20:31
this information has all been captured now in "Requirements for Cloning/Deriving/Reusing/ in Sinopia" https://docs.google.com/document/d/18mrYqgMWJYokkCFcLWO0UPSlTBH3m2vkzWSXAPT4Uzk/ and individual tickets will be made for the various aspects of this feature

**Closed by michelleif** 2019-09-08 20:31 UTC
Labels: Entering Metadata, User Acceptance Test, question, stretch
