### ISSUE TITLE
Entity Creation Support if Look-up Fails

### ISSUE THREAD

**Issue by cmh2166** [LD4P/sinopia#64] opened 2018-07-17 23:32 UTC
L1. If no entity is available via look-ups, be able to create one in ISNI, NACO, or other established places.

This MVP could be:
1. Link to place where person can create a resource or docs for creation
2. Alternative is they can create local agent (see #65) or other entity in sandbox then sameAs that later

Neither of these negate ability to copy / paste URI into field value.

**Comment by michelleif** [comment] 2018-08-23 21:57
Harvard needs ability to create entities in Wikidata (especially) and ISNI from the sandbox. Further detail coming.

**Comment by michelleif** [comment] 2018-10-02 21:02
update: Harvard does not expect to be able to do this in the first work cycle.

**Comment by michelleif** [comment] 2018-10-02 21:04
duplicate of #65

**Closed by michelleif** 2018-10-02 21:05 UTC
Labels: duplicate
