### ISSUE TITLE
Sandbox editor has existing metadata lookup

### ISSUE THREAD

**Issue by cmharlow** [LD4P/sinopia#11] opened 2018-07-05 23:39 UTC
Need further clarification on what search options exists on the data (i.e. by author, date, meta-author [cataloger], date of record creation, whatever).

Two existing "filters" or search fields: 
1. metadata according to metadata creator 
2. compliance with PCC guidelines

lookup within the editor environment for the local / working store

**Comment by michelleif** [comment] 2019-03-12 20:27
duplicate of #51

**Closed by michelleif** 2019-03-12 20:27 UTC
