### ISSUE TITLE
Ability to CRUD Forms

### ISSUE THREAD

**Issue by cmh2166** [LD4P/sinopia#41] opened 2018-07-12 22:39 UTC
A36: Create new property or class if one doesn't exist, and add it to the list of classes and properties that can be used for setting up forms and for entering metadata. (Not talking here about pushing/proposing new properties/classes into an ontology/vocabulary somewhere else)

**Comment by ndushay** [comment] 2018-09-25 22:43
duplicate of other tickets - covered by profile editor functionality

**Closed by ndushay** 2018-09-25 22:43 UTC
Labels: Profiles, to do
